spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/Test
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
logging:
  level:
    org.springframework.boot.autoconfigure: debug