
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/demo
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
logging:
  level:
    org.springframework.boot.autoconfigure: debug
mybatis:
  mapper-locations: classpath:mapper/*.xml
person:
  name: kkkkk${random.uuid}
  age: ${random.int}
  happy: false
  birth: 2019/11/02
  maps: {k1: v1,K2: v2}
  lists:
    - code
    - music
    - girl
  dog:
    name: 旺财
    age: 3
